function addHomeContract(
    houseName,
    houseStairs,
    houseRoom,
    houseAddress,
    houseRegistry,
    houseTypes,
    houseStructure,
    houseHouseholds,
    houseCompletionReignTitle,
    houseCompletionTime,
    houseConstructionReignTitle,
    houseConstructionTime,
    houseRoomNumber,
    houseRoomLayout,
    houseFloorSpace,
    houseBalconyArea,
    electricityWithoutWith,
    electricityFormatAmpere,
    electricityFormatMeter1,
    electricityFormatMeter2,
    electricityFormatMeter3,
    electricityNote,
    gasWithoutWith,
    gasFormat1,
    gasFormat2,
    gasFormatMeter1,
    gasFormatMeter2,
    gasFormatMeter3,
    gasNote,
    stoveWithoutWith,
    stoveFormat1,
    stoveFormat2,
    stoveFormat3,
    stoveNote,
    aqueductWithoutWith,
    aqueductFormat1,
    aqueductFormat2,
    aqueductFormat3,
    aqueductNote,
    sewerageWithoutWith,
    sewerageFormat1,
    sewerageFormat2,
    sewerageNote,
    counterWithoutWith,
    counterFormat1,
    counterFormat2,
    counterFormat3,
    counterFormat4,
    counterNote,
    toiletWithoutWith,
    toiletFormat1,
    toiletFormat2,
    toiletFormat3,
    toiletFormat4,
    toiletFormat5,
    toiletNote,
    bathroomWithoutWith,
    bathroomFormatShowerWithoutWith,
    bathroomFormatOther,
    bathroomNote,
    sinkWithoutWith,
    sinkFormat1,
    sinkFormat2,
    sinkFormat3,
    sinkFormat4Other,
    sinkNote,
    washingMachinePlaceWithoutWith,
    washingMachinePlaceFormat,
    washingMachinePanWithoutWith,
    washingMachinePlaceNote,
    waterHeaterWithoutWith,
    waterHeater,
    waterHeaterFormat1,
    waterHeaterFormat2,
    waterHeaterFormat3,
    waterHeaterFormat4,
    waterHeaterFormat5Other,
    waterHeaterNote,
    airConditionerWithoutWith,
    airConditioner,
    airConditionerPlumbingSleeveWithoutWith,
    airConditionerFormat1,
    airConditionerFormat2Other,
    airConditioningEquipmentNote,
    lightWithoutWith,
    lightFormat,
    lightNote,
    furnitureWithoutWith,
    furnitureFormat1,
    furnitureFormat2,
    furnitureFormat3,
    furnitureFormat4Other,
    furnitureNote,
    tvWithoutWith,
    tvFormat,
    tvNote,
    catvWithoutWith,
    catvFormat,
    catvNote,
    internetWithoutWith,
    internetFormat,
    internetNote,
    storehouseWithoutWith,
    storehouseFormat,
    storehouseNote,
    patioWithoutWith,
    patioFormat,
    patioNote,
    roofBalconyWithoutWith,
    roofBalconyFormat,
    roofBalconyNote,
    keyWithoutWith,
    keyNumber,
    moreKey,
    keyNote,
    houseFacilities1,
    houseFacilities1WithoutWith,
    houseFacilities1Format,
    houseFacilities1Note,
    houseFacilities2,
    houseFacilities2WithoutWith,
    houseFacilities2Format,
    houseFacilities2Note,
    houseFacilities3,
    houseFacilities3WithoutWith,
    houseFacilities3Format,
    houseFacilities3Note,
    liftWithoutWith,
    liftRentState,
    liftNote,
    electronicLockWithoutWith,
    electronicLockRentState,
    electronicLockNote,
    mailboxWithoutWith,
    mailboxRentState,
    mailboxNote,
    deliveryBoxWithoutWith,
    deliveryBoxRentState,
    deliveryBoxNote,
    trunkRoomWithoutWith,
    trunkRoomHaveOrHavent,
    trunkRoomNote,
    parkingGarageWithoutWith,
    parkingGarageHaveOrHavent,
    parkingGarageNote,
    bicycleParkingWithoutWith,
    bicycleParkingHaveOrHavent,
    bicycleParkingNote,
    scooterParkingWithoutWith,
    scooterParkingHaveOrHavent,
    scooterParkingNote,
    publicFacilities1,
    publicFacilities1WithoutWith,
    publicFacilities1RentState,
    publicFacilities1Note,
    publicFacilities2,
    publicFacilities2WithoutWith,
    publicFacilities2RentState,
    publicFacilities2Note,
    publicFacilitiesNote,
    contractStartTime,
    contractEndTime,
    contractTime,
    deliveryDateOfContractTimeObject,
    monthly,
    rentPaymentDeadlineMonth,
    rentPaymentDeadlineDate,
    administrationFee,
    administrationFeeMonth,
    administrationFeeDate,
    securityDepositMonth,
    securityDepositDate,
    parkingFee,
    parkingFeeNote,
    ancillaryFacilityFee,
    ancillaryFacilityFeeNote,
    cashGift,
    cashGiftNote,
    monthlyPaymentMethod,
    monthlyPaymentMethodOther,
    beneficiaryBankAndBranchName,
    accountType,
    accountNumber,
    accountHolder,
    transferFeeBearer,
    bearerAddress,
    keysLendAndNumber1,
    keysLendAndNumber2,
    keysLendAndNumber3,
    landlordName,
    landlordPhone,
    landlordAddress,
    realEstateAgencyName,
    realEstateAgencyPhone,
    realEstateAgencyAddress,
    registrationSystem,
    registrationNumber,
    administrantName,
    houseOwnerAddress,
    houseOwnerName,
    tenantName,
    tenantAge,
    residentName1,
    residentAge1,
    residentName2,
    residentAge2,
    residentName3,
    residentAge3,
    residentName4,
    residentAge4,
    residentName5,
    residentAge5,
    residentName6,
    residentAge6,
    emergencyContactName,
    emergencyContactRelationshipWithBorrowers,
    emergencyContactAddress,
    emergencyContactAddressPhone,
    emergencyContactWorkplace,
    emergencyContactWorkplaceWorkPhone,
    emergencyContactMobileNumber,
    maximumAmount,
    renewalAmountMonthWithoutWith,
    renewalAmountMonth,
    renewalAmountDate,
    renewalAmountWithoutNote,
    specialTerms,
    jointGuaranteeContractDate,
    landlordAddress2,
    landlordName2,
    landlordPhone2,
    tenantAddress,
    tenantName2,
    tenantPhone,
    jointGuarantorAddress,
    jointGuarantorName,
    jointGuarantorPhone,
    maximumAmount2) {

    let objPostData = {
        //對照req:上面addHome方法參數
        houseName: houseName,
        houseStairs: houseStairs,
        houseRoom: houseRoom,
        houseAddress: houseAddress,
        houseRegistry: houseRegistry,
        houseTypes: houseTypes,
        houseStructure: houseStructure,
        houseHouseholds: houseHouseholds,
        houseCompletionReignTitle: houseCompletionReignTitle,
        houseCompletionTime: houseCompletionTime,
        houseConstructionReignTitle: houseConstructionReignTitle,
        houseConstructionTime: houseConstructionTime,
        houseRoomNumber: houseRoomNumber,
        houseRoomLayout: houseRoomLayout,
        houseFloorSpace: houseFloorSpace,
        houseBalconyArea: houseBalconyArea,
        electricityWithoutWith: electricityWithoutWith,
        electricityFormatAmpere: electricityFormatAmpere,
        electricityFormatMeter1: electricityFormatMeter1,
        electricityFormatMeter2: electricityFormatMeter2,
        electricityFormatMeter3: electricityFormatMeter3,
        electricityNote: electricityNote,
        gasWithoutWith: gasWithoutWith,
        gasFormat1: gasFormat1,
        gasFormat2: gasFormat2,
        gasFormatMeter1: gasFormatMeter1,
        gasFormatMeter2: gasFormatMeter2,
        gasFormatMeter3: gasFormatMeter3,
        gasNote: gasNote,
        stoveWithoutWith: stoveWithoutWith,
        stoveFormat1: stoveFormat1,
        stoveFormat2: stoveFormat2,
        stoveFormat3: stoveFormat3,
        stoveNote: stoveNote,
        aqueductWithoutWith: aqueductWithoutWith,
        aqueductFormat1: aqueductFormat1,
        aqueductFormat2: aqueductFormat2,
        aqueductFormat3: aqueductFormat3,
        aqueductNote: aqueductNote,
        sewerageWithoutWith: sewerageWithoutWith,
        sewerageFormat1: sewerageFormat1,
        sewerageFormat2: sewerageFormat2,
        sewerageNote: sewerageNote,
        counterWithoutWith: counterWithoutWith,
        counterFormat1: counterFormat1,
        counterFormat2: counterFormat2,
        counterFormat3: counterFormat3,
        counterFormat4: counterFormat4,
        counterNote: counterNote,
        toiletWithoutWith: toiletWithoutWith,
        toiletFormat1: toiletFormat1,
        toiletFormat2: toiletFormat2,
        toiletFormat3: toiletFormat3,
        toiletFormat4: toiletFormat4,
        toiletFormat5: toiletFormat5,
        toiletNote: toiletNote,
        bathroomWithoutWith: bathroomWithoutWith,
        bathroomFormatShowerWithoutWith: bathroomFormatShowerWithoutWith,
        bathroomFormatOther: bathroomFormatOther,
        bathroomNote: bathroomNote,
        sinkWithoutWith: sinkWithoutWith,
        sinkFormat1: sinkFormat1,
        sinkFormat2: sinkFormat2,
        sinkFormat3: sinkFormat3,
        sinkFormat4Other: sinkFormat4Other,
        sinkNote: sinkNote,
        washingMachinePlaceWithoutWith: washingMachinePlaceWithoutWith,
        washingMachinePlaceFormat: washingMachinePlaceFormat,
        washingMachinePanWithoutWith: washingMachinePanWithoutWith,
        washingMachinePlaceNote: washingMachinePlaceNote,
        waterHeaterWithoutWith: waterHeaterWithoutWith,
        waterHeater: waterHeater,
        waterHeaterFormat1: waterHeaterFormat1,
        waterHeaterFormat2: waterHeaterFormat2,
        waterHeaterFormat3: waterHeaterFormat3,
        waterHeaterFormat4: waterHeaterFormat4,
        waterHeaterFormat5Other: waterHeaterFormat5Other,
        waterHeaterNote: waterHeaterNote,
        airConditioningEquipmentWithoutWith: airConditionerWithoutWith,
        airConditioner: airConditioner,
        airConditionerPlumbingSleeveWithoutWith: airConditionerPlumbingSleeveWithoutWith,
        airConditionerFormat1: airConditionerFormat1,
        airConditionerFormat2Other: airConditionerFormat2Other,
        airConditioningEquipmentNote: airConditioningEquipmentNote,
        lightWithoutWith: lightWithoutWith,
        lightFormat: lightFormat,
        lightNote: lightNote,
        furnitureWithoutWith: furnitureWithoutWith,
        furnitureFormat1: furnitureFormat1,
        furnitureFormat2: furnitureFormat2,
        furnitureFormat3: furnitureFormat3,
        furnitureFormat4Other: furnitureFormat4Other,
        furnitureNote: furnitureNote,
        tvWithoutWith: tvWithoutWith,
        tvFormat: tvFormat,
        tvNote: tvNote,
        catvWithoutWith: catvWithoutWith,
        catvFormat: catvFormat,
        catvNote: catvNote,
        internetWithoutWith: internetWithoutWith,
        internetFormat: internetFormat,
        internetNote: internetNote,
        storehouseWithoutWith: storehouseWithoutWith,
        storehouseFormat: storehouseFormat,
        storehouseNote: storehouseNote,
        patioWithoutWith: patioWithoutWith,
        patioFormat: patioFormat,
        patioNote: patioNote,
        roofBalconyWithoutWith: roofBalconyWithoutWith,
        roofBalconyFormat: roofBalconyFormat,
        roofBalconyNote: roofBalconyNote,
        keyWithoutWith: keyWithoutWith,
        keyNumber: keyNumber,
        moreKey: moreKey,
        keyNote: keyNote,
        houseFacilities1: houseFacilities1,
        houseFacilities1WithoutWith: houseFacilities1WithoutWith,
        houseFacilities1Format: houseFacilities1Format,
        houseFacilities1Note: houseFacilities1Note,
        houseFacilities2: houseFacilities2,
        houseFacilities2WithoutWith: houseFacilities2WithoutWith,
        houseFacilities2Format: houseFacilities2Format,
        houseFacilities2Note: houseFacilities2Note,
        houseFacilities3: houseFacilities3,
        houseFacilities3WithoutWith: houseFacilities3WithoutWith,
        houseFacilities3Format: houseFacilities3Format,
        houseFacilities3Note: houseFacilities3Note,
        liftWithoutWith: liftWithoutWith,
        liftRentState: liftRentState,
        liftNote: liftNote,
        electronicLockWithoutWith: electronicLockWithoutWith,
        electronicLockRentState: electronicLockRentState,
        electronicLockNote: electronicLockNote,
        mailboxWithoutWith: mailboxWithoutWith,
        mailboxRentState: mailboxRentState,
        mailboxNote: mailboxNote,
        deliveryBoxWithoutWith: deliveryBoxWithoutWith,
        deliveryBoxRentState: deliveryBoxRentState,
        deliveryBoxNote: deliveryBoxNote,
        trunkRoomWithoutWith: trunkRoomWithoutWith,
        trunkRoomHaveOrHavent: trunkRoomHaveOrHavent,
        trunkRoomNote: trunkRoomNote,
        parkingGarageWithoutWith: parkingGarageWithoutWith,
        parkingGarageHaveOrHavent: parkingGarageHaveOrHavent,
        parkingGarageNote: parkingGarageNote,
        bicycleParkingWithoutWith: bicycleParkingWithoutWith,
        bicycleParkingHaveOrHavent: bicycleParkingHaveOrHavent,
        bicycleParkingNote: bicycleParkingNote,
        scooterParkingWithoutWith: scooterParkingWithoutWith,
        scooterParkingHaveOrHavent: scooterParkingHaveOrHavent,
        scooterParkingNote: scooterParkingNote,
        publicFacilities1: publicFacilities1,
        publicFacilities1WithoutWith: publicFacilities1WithoutWith,
        publicFacilities1RentState: publicFacilities1RentState,
        publicFacilities1Note: publicFacilities1Note,
        publicFacilities2: publicFacilities2,
        publicFacilities2WithoutWith: publicFacilities2WithoutWith,
        publicFacilities2RentState: publicFacilities2RentState,
        publicFacilities2Note: publicFacilities2Note,
        publicFacilitiesNote: publicFacilitiesNote,
        contractStartTime: contractStartTime,
        contractEndTime: contractEndTime,
        contractTime: contractTime,
        deliveryDateOfContractTimeObject: deliveryDateOfContractTimeObject,
        monthly: monthly,
        rentPaymentDeadlineMonth: rentPaymentDeadlineMonth,
        rentPaymentDeadlineDate: rentPaymentDeadlineDate,
        administrationFee: administrationFee,
        administrationFeeMonth: administrationFeeMonth,
        administrationFeeDate: administrationFeeDate,
        securityDepositMonth: securityDepositMonth,
        securityDepositDate: securityDepositDate,
        parkingFee: parkingFee,
        parkingFeeNote: parkingFeeNote,
        ancillaryFacilityFee: ancillaryFacilityFee,
        ancillaryFacilityFeeNote: ancillaryFacilityFeeNote,
        cashGift: cashGift,
        cashGiftNote: cashGiftNote,
        monthlyPaymentMethod: monthlyPaymentMethod,
        monthlyPaymentMethodOther: monthlyPaymentMethodOther,
        beneficiaryBankAndBranchName: beneficiaryBankAndBranchName,
        accountType: accountType,
        accountNumber: accountNumber,
        accountHolder: accountHolder,
        transferFeeBearer: transferFeeBearer,
        bearerAddress: bearerAddress,
        keysLendAndNumber1: keysLendAndNumber1,
        keysLendAndNumber2: keysLendAndNumber2,
        keysLendAndNumber3: keysLendAndNumber3,
        landlordName: landlordName,
        landlordPhone: landlordPhone,
        landlordAddress: landlordAddress,
        realEstateAgencyName: realEstateAgencyName,
        realEstateAgencyPhone: realEstateAgencyPhone,
        realEstateAgencyAddress: realEstateAgencyAddress,
        registrationSystem: registrationSystem,
        registrationNumber: registrationNumber,
        administrantName: administrantName,
        houseOwnerAddress: houseOwnerAddress,
        houseOwnerName: houseOwnerName,
        tenantName: tenantName,
        tenantAge: tenantAge,
        residentName1: residentName1,
        residentAge1: residentAge1,
        residentName2: residentName2,
        residentAge2: residentAge2,
        residentName3: residentName3,
        residentAge3: residentAge3,
        residentName4: residentName4,
        residentAge4: residentAge4,
        residentName5: residentName5,
        residentAge5: residentAge5,
        residentName6: residentName6,
        residentAge6: residentAge6,
        emergencyContactName: emergencyContactName,
        emergencyContactRelationshipWithBorrowers: emergencyContactRelationshipWithBorrowers,
        emergencyContactAddress: emergencyContactAddress,
        emergencyContactAddressPhone: emergencyContactAddressPhone,
        emergencyContactWorkplace: emergencyContactWorkplace,
        emergencyContactWorkplaceWorkPhone: emergencyContactWorkplaceWorkPhone,
        emergencyContactMobileNumber: emergencyContactMobileNumber,
        maximumAmount: maximumAmount,
        renewalAmountWithoutWith: renewalAmountMonthWithoutWith,
        renewalAmountMonth: renewalAmountMonth,
        renewalAmountDate: renewalAmountDate,
        renewalAmountWithoutNote: renewalAmountWithoutNote,
        specialTerms: specialTerms,
        jointGuaranteeContractDate: jointGuaranteeContractDate,
        // landlordAddress2,
        // landlordName2,
        // landlordPhone2,
        tenantAddress: tenantAddress,
        // tenantName2,
        tenantPhone: tenantPhone,
        jointGuarantorAddress: jointGuarantorAddress,
        jointGuarantorName: jointGuarantorName,
        jointGuarantorPhone: jointGuarantorPhone
        // maximumAmount2

    }


    $.ajax({
        url: 'http://localhost:8080/api/addHomeContract',
        method: 'POST',
        // 以下兩行為 Json固定寫法：利用json做傳遞
        contentType: 'application/json',
        //宣告資料型態為JSON
        dataType: 'json',
        //將後端返回的entity轉成JSON格式
        data: JSON.stringify(objPostData),
        // 當成功時就會執行function括號裡的參數
        success: function (residentialBuildingLeaseAgreementRes) {
            // 對照res的內容，可以接收後端回傳的資料，且呈現於前端(等於後面是自定義名稱)
            let { residentialBuildingLeaseAgreement, contractHistory, message } = residentialBuildingLeaseAgreementRes
            alert(message)

            //抓取後端資料 --> 轉換JSON格式 --> 設定到前端
            sessionStorage.setItem('residentialBuildingLeaseAgreement', JSON.stringify(residentialBuildingLeaseAgreement))
            sessionStorage.setItem('contractHistory', JSON.stringify(contractHistory))

            if (message === '増加成功') {
                //如果返回訊息為「増加成功」--> 跳轉頁面
                window.location.href = "/infoHome.html"
            }


        },


        error: function (e) {
            console.log(e)
            alert('Failed')
        },
    }

    )

}


function updateContract(
    houseName,
    houseRoom,
    houseAddress,
    contractStartTime,
    contractEndTime,
    contractTime,
    deliveryDateOfContractTimeObject,
    monthly,
    rentPaymentDeadlineMonth,
    rentPaymentDeadlineDate,
    administrationFee,
    administrationFeeMonth,
    administrationFeeDate,
    securityDepositMonth,
    securityDepositDate,
    parkingFee,
    parkingFeeNote,
    ancillaryFacilityFee,
    ancillaryFacilityFeeNote,
    cashGift,
    cashGiftNote,
    monthlyPaymentMethod,
    monthlyPaymentMethodOther,
    beneficiaryBankAndBranchName,
    accountType,
    accountNumber,
    accountHolder,
    transferFeeBearer,
    bearerAddress,
    keysLendAndNumber1,
    keysLendAndNumber2,
    keysLendAndNumber3,
    tenantName,
    tenantAge,
    residentName1,
    residentAge1,
    residentName2,
    residentAge2,
    residentName3,
    residentAge3,
    residentName4,
    residentAge4,
    residentName5,
    residentAge5,
    residentName6,
    residentAge6,
    emergencyContactName,
    emergencyContactRelationshipWithBorrowers,
    emergencyContactAddress,
    emergencyContactAddressPhone,
    emergencyContactWorkplace,
    emergencyContactWorkplaceWorkPhone,
    emergencyContactMobileNumber,
    jointGuaranteeContractDate,
    landlordAddress2,
    landlordName2,
    landlordPhone2,
    tenantAddress,
    tenantName2,
    tenantPhone,
    jointGuarantorAddress,
    jointGuarantorName,
    jointGuarantorPhone,
    maximumAmount2
) {
    let objPostData2 = {
        houseName: houseName,
        houseRoom: houseRoom,
        houseAddress: houseAddress,
        contractStartTime: contractStartTime,
        contractEndTime: contractEndTime,
        contractTime: contractTime,
        deliveryDateOfContractTimeObject: deliveryDateOfContractTimeObject,
        monthly: monthly,
        rentPaymentDeadlineMonth: rentPaymentDeadlineMonth,
        rentPaymentDeadlineDate: rentPaymentDeadlineDate,
        administrationFee: administrationFee,
        administrationFeeMonth: administrationFeeMonth,
        administrationFeeDate: administrationFeeDate,
        securityDepositMonth: securityDepositMonth,
        securityDepositDate: securityDepositDate,
        parkingFee: parkingFee,
        parkingFeeNote: parkingFeeNote,
        ancillaryFacilityFee: ancillaryFacilityFee,
        ancillaryFacilityFeeNote: ancillaryFacilityFeeNote,
        cashGift: cashGift,
        cashGiftNote: cashGiftNote,
        monthlyPaymentMethod: monthlyPaymentMethod,
        monthlyPaymentMethodOther: monthlyPaymentMethodOther,
        beneficiaryBankAndBranchName: beneficiaryBankAndBranchName,
        accountType: accountType,
        accountNumber: accountNumber,
        accountHolder: accountHolder,
        transferFeeBearer: transferFeeBearer,
        bearerAddress: bearerAddress,
        keysLendAndNumber1: keysLendAndNumber1,
        keysLendAndNumber2: keysLendAndNumber2,
        keysLendAndNumber3: keysLendAndNumber3,
        tenantName: tenantName,
        tenantAge: tenantAge,
        residentName1: residentName1,
        residentAge1: residentAge1,
        residentName2: residentName2,
        residentAge2: residentAge2,
        residentName3: residentName3,
        residentAge3: residentAge3,
        residentName4: residentName4,
        residentAge4: residentAge4,
        residentName5: residentName5,
        residentAge5: residentAge5,
        residentName6: residentName6,
        residentAge6: residentAge6,
        emergencyContactName: emergencyContactName,
        emergencyContactRelationshipWithBorrowers: emergencyContactRelationshipWithBorrowers,
        emergencyContactAddress: emergencyContactAddress,
        emergencyContactAddressPhone: emergencyContactAddressPhone,
        emergencyContactWorkplace: emergencyContactWorkplace,
        emergencyContactWorkplaceWorkPhone: emergencyContactWorkplaceWorkPhone,
        emergencyContactMobileNumber: emergencyContactMobileNumber,
        jointGuaranteeContractDate: jointGuaranteeContractDate,
        landlordAddress: landlordAddress2,
        landlordName: landlordName2,
        landlordPhone: landlordPhone2,
        tenantAddress: tenantAddress,
        tenantName: tenantName2,
        tenantPhone: tenantPhone,
        jointGuarantorAddress: jointGuarantorAddress,
        jointGuarantorName: jointGuarantorName,
        jointGuarantorPhone: jointGuarantorPhone,
        maximumAmount: maximumAmount2

    }
    $.ajax({
        url: 'http://localhost:8080/api/updateContract',
        method: 'POST',
        // 以下兩行為 Json固定寫法：利用json做傳遞
        contentType: 'application/json',
        dataType: 'json',
        //傳送資料
        data: JSON.stringify(objPostData2),
        // 當成功時就會執行function括號裡的參數
        success: function (residentialBuildingLeaseAgreementRes) {
            // 對照res的內容，可以接收後端回傳的資料，且呈現於前端(等於後面是自定義名稱)
            let { residentialBuildingLeaseAgreement, contractHistory, message } = residentialBuildingLeaseAgreementRes
            alert(message)

            //抓取後端資料 --> 轉換JSON格式 --> 設定到前端(''內為自定義名)
            sessionStorage.setItem('residentialBuildingLeaseAgreement', JSON.stringify(residentialBuildingLeaseAgreement))
            sessionStorage.setItem('contractHistory', JSON.stringify(contractHistory))

            if (message === 'アップデート成功') {

                //如果返回訊息為「アップデート成功」--> 跳轉頁面
                window.location.href = "/printUpdateHomesContract.html"
                //跳新分頁
                // window.open('/update.html', '_blank')
            }
        },

        error: function (e) {
            console.log(e)
            alert('Failed')
        },
    }
    )
}




